<?php

echo $block->getLayout()

           ->createBlock('Magento\Cms\Block\Block')

           ->setBlockId('best-sellers')

           ->toHtml();

?>

<!-- 
<script>
    require([
        'jquery',
        'owlCarousel'
    ],function($,owlCarousel) {
        $('.owl-carousel').owlCarousel({
            items:4,
            lazyLoad:true,
            loop:true,
            nav:true
            margin:10
        });
    });

</script> -->


<!-- 
<div class="owl-carousel owl-theme">
    <div><img src="https://placehold.it/350x250&text=4" alt=""></div>
    <div><img src="https://placehold.it/350x250&text=5" alt=""></div>
    <div><img src="https://placehold.it/350x250&text=6" alt=""></div>
    <div><img src="https://placehold.it/350x250&text=7" alt=""></div>
    <div><img src="https://placehold.it/350x250&text=8" alt=""></div>
    <div><img src="https://placehold.it/350x400&text=9" alt=""></div>
    <div><img src="https://placehold.it/350x400&text=10" alt=""></div>
    <div><img src="https://placehold.it/350x450&text=11" alt=""></div>
</div> -->